### ISSUE TITLE
Not working in mobile safari 

### ISSUE THREAD

**Issue by Zettersten** [cryptodescriptor/frosted-panel#1] opened 2019-08-12 01:55 UTC
Frost does not work in iOS Safari

iOS 12
iPhone X

![4620222A-CEFC-4DF2-A9BC-87CE46427B26](https://user-images.githubusercontent.com/183147/62842767-681cd080-bc82-11e9-92ed-2d1e9abadfa1.png)

**Comment by cryptodescriptor** [comment] 2019-08-12 05:00
I tested in Safari 12 desktop using a website which didn't let me test Safari 12 mobile edition, but it did let me test the desktop version 12. The same issue you have demonstrated occured. The problem was caused by the `href` attribute of `image` element being unsupported in Safari. I have reverted back to using the old `xlink:href` attribute instead, and it seems to be working now in Safari 12. 

I was also able to test Safari 11 using the website, and unfortunately the blur effect does not seem to work at all, and the panning transition seems to not work as it should. 

Am I correct in thinking most people are now using Safari 12? Are you running Safari 12 on your Iphone X? Can you please confirm whether or not the demo is now displaying correctly?

https://cryptodescriptor.github.io/frosted-panel

**Comment by Zettersten** [comment] 2019-08-12 14:10
Yes I’m using Safari 12.

There seems to be an issue in vertical mode.

When I rotate my phone, it works correctly.

**Comment by cryptodescriptor** [comment] 2019-08-12 16:09
Does the panel image look aligned with the background-image? Do you mean the blur isn't working in vertical mode? 

edit: I see what you mean, just the blur effect, I was able to reproduce the issue. Working on a fix.

**Comment by cryptodescriptor** [comment] 2019-08-12 17:56
I seem to have fixed it by adding an attribute `filterRes="1200"` to the `filter` element. Can you please confirm it is fixed in your Safari version and I will push the release.

**Comment by cryptodescriptor** [comment] 2019-08-13 18:56
Closing this issue because I have done multiple tests and it looks fixed. Feel free to re-open if you have any other issues.

**Closed as completed by cryptodescriptor** 2019-08-13 18:56 UTC
